excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://flyingoat.github.io
title: flyingoat
tagline: Anthropologist. Aspiring queer-anarcho-feminist. Lives in animated suspension from 9-5 and self medicates with cruel optimism (L.Berlant). Wannabe Varoufakis groupie.
description: Poems. Writing. Thoughts. Nightmares. 
paginate: 5